// To print simple word 
console.log("Hello world");

// variables
let name="ram";
var a = "shree";
const b=45;
console.log(a,b,name);

// To data type 
// To number 
let n = 20;
let n1=16.00;
// To string 
let name1 ="Ram";
let name2= false;
// TO object 
let person={
    name:"ram",
    age:34,
    city:"pune"
};
// To array 
let number =[1,2,3,4,5,6,7,8,9,0];
// undfine 
let name4 ;
// To null
let name5 = null;
// console.log(person)
// console.log(n2)
console.log(n1)
console.log(name1);
console.log(name2);
console.log(name4);
console.log(name5);

// string 
// simple string
x = "Navnath"
y = "Priya"
z ="Deshmukh"
console.log(x);
// console.log(z + " "+ y + " " + x);//To concatination
let s ='we welcome ${z}${y}${x}';
// console.log(s);
console.log((x[0]));//To access chracter by index 
console.log((x.length));//To check length of string
console.log((x.toUpperCase()));//uppercase 
// console.log(x.toLowercase());//lowercase
console.log(x.indexOf('n'))//indexof
console.log(x.includes('a'))//includes to check 
console.log(x.trim());//To remove white space at start and end
console.log(x.slice(1,3)) //slice
console.log(x.split()); //split

// typeof
let age = 20;
let address= {};
let names = "Ram";
let city =[];
let course;
console.log(typeof age);
console.log(typeof address);
console.log(typeof names);
console.log(typeof city);
console.log(typeof course);

// operator(op) 
// arithmetic op
c=34,d=90;
console.log(c + d);
console.log(c - d);
console.log(c * d);
console.log(c / d);
console.log(c % d);
// increment and decrement op
console.log(c++);
console.log(++c);
console.log(c--);
console.log(--c);
// logical op
console.log((c > d)||(d<c));
console.log((c > d)&&(d<c));
console.log((c > d)==(d<c));
console.log((c > d)===(d<c));
console.log((c > d)!=(d<c));

// type coercion
// console.log((c + d));





// array -->
let x1=[99,100];
let x2=[1,2,3,4,5,6,7,8,9,0]
console.log(x2[9]);//Reading array
console.log(x2[0]=6);//writing array
console.log(x2)
console.log(x2.length);//length
console.log(x2.push(11)); //push
console.log(x2)
console.log(x2.pop()) //pop
console.log(x2)
console.log(x2.indexOf(8)) //indexof function
console.log(x2);
console.log(x2.concat(x1));//concat function
// console.log(x)

// loops or control flow


